server:
    port: 8080

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
        fetch-registry: true

spring:
    application:
        name: gateway
    cloud:
        gateway:
            server:
                webflux:
                    # globalcors:
                    #     cors-configurations:
                    #     '[/**]':
                    #         allowedOrigins:
                    #         - "https://domain.com"
                    #         - "http://localhost:3000"
                    #         allowedMethods:
                    #         - GET
                    #         - POST
                    #         - PUT
                    #         - DELETE
                    #         allowedHeaders: "*"
                    #         allowCredentials: true
                    routes:
                      - id: service-registry
                        uri: http://localhost:8081
                        predicates:
                        - Path=/service-registry
                      - id: users-service
                        uri: http://localhost:8082
                        predicates:
                            - Path=/api/user, /auth/register, /auth/login
                      - id: posts-service
                        uri: http://localhost:8083
                        predicates:
                            - Path=/api/post

            
